name: Expo Doctor (expo)

on:
  push:
    branches:
      - main
      - master
    paths:
      - 'package.json'
      - 'yarn.lock'
  pull_request:
    paths:
      - 'package.json'
      - 'yarn.lock'

jobs:
  doctor:
    name: Expo Doctor (expo)
    runs-on: ubuntu-latest

    steps:
      - name: 📦 Checkout project repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 📦 Setup Node + YARN + install deps
        uses: ./.github/actions/setup-node

      - name: Run prebuild
        run: yarn prebuild

      - name: 🚑 Run Doctor Checks
        run: rm -rf ios android && yarn run doctor
